title: Ahmed Khaled
description: "Teaching computers, and humans, how to learn"
author: Ahmed Khaled

markdown: kramdown
kramdown:
  input: GFM

permalink: /blog/:year/:month/:day/:title/
timezone: Africa/Cairo

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
